/**
 * Live content: the manifest generated by scripts/update-content.mjs and
 * refreshed every 6 hours by the GitHub Actions cron. The app fetches it from
 * the repository (raw GitHub, CORS-friendly), falls back to the bundled copy,
 * caches it, and re-checks while running.
 */
import { store, bus } from './kernel';

export interface NewsItem { id: string; title: string; summary: string; url: string; publishedAt: string | null; header: string | null; thumb: string | null; forever: boolean; }
export interface ManifestEvent { id: string; date: string; endDate?: string; title: string; kind: 'launch' | 'beta' | 'raid' | 'info'; desc?: string; }
export interface Manifest { version: number; checkedAt: string; launchUtc: string; news: NewsItem[]; forever: Record<string, string | null>; events: ManifestEvent[]; notice: string | null; }

export const CONTENT_URL = store.get('content.url', 'https://raw.githubusercontent.com/MixMasterFei/GeekOS/main/public/data/manifest.json');
const LOCAL_URL = '/data/manifest.json';
const REFRESH_MS = 6 * 60 * 60 * 1000;

let current: Manifest | null = store.get<Manifest | null>('content.manifest', null);
let timer = 0;

export const content = {
  get manifest() { return current; },
  get lastChecked(): number { return store.get('content.lastChecked', 0); },
  get lastFetchedAt(): number { return store.get('content.fetchedAt', 0); },
  get source(): string { return store.get('content.source', 'bundled'); },

  async refresh(force = false): Promise<{ manifest: Manifest | null; fresh: NewsItem[]; error?: string }> {
    const before = current;
    let m: Manifest | null = null; let error: string | undefined; let source = 'remote';
    try { const r = await fetch(CONTENT_URL + (force ? `?t=${Date.now()}` : ''), { cache: force ? 'no-store' : 'default' }); if (!r.ok) throw new Error(`${r.status}`); m = await r.json(); }
    catch (e: any) { error = `remote: ${e?.message ?? e}`; try { const r = await fetch(LOCAL_URL); if (r.ok) { m = await r.json(); source = 'bundled'; } } catch (e2: any) { error += ` · bundled: ${e2?.message ?? e2}`; } }
    store.set('content.lastChecked', Date.now());
    if (!m) return { manifest: current, fresh: [], error };
    const known = new Set((before?.news ?? []).map(n => n.id));
    const fresh = before ? m.news.filter(n => !known.has(n.id)) : [];
    current = m; store.set('content.manifest', m); store.set('content.fetchedAt', Date.now()); store.set('content.source', source);
    bus.emit('content:update', { manifest: m, fresh, source });
    return { manifest: m, fresh, error };
  },

  start() {
    const due = Date.now() - this.lastChecked > REFRESH_MS;
    if (due || !current) this.refresh().catch(() => {});
    clearInterval(timer);
    timer = window.setInterval(() => this.refresh().catch(() => {}), 30 * 60 * 1000); // check every 30 min; the manifest itself changes ~every 6h
    addEventListener('online', () => this.refresh().catch(() => {}));
  },
  stop() { clearInterval(timer); },
  news(onlyForever = false): NewsItem[] { const n = current?.news ?? []; return onlyForever ? n.filter(x => x.forever) : n; },
  launchUtc(): number { const s = current?.launchUtc; const t = s ? Date.parse(s) : NaN; return Number.isFinite(t) ? t : Date.UTC(2026, 10, 4, 23, 0, 0); },
  markNewsSeen() { store.set('content.newsSeen', (current?.news ?? []).map(n => n.id)); },
  unseenNews(): NewsItem[] { const seen = new Set(store.get<string[]>('content.newsSeen', [])); return (current?.news ?? []).filter(n => !seen.has(n.id)); },
};
